// Copyright 2026 Element-NSPA <johnstonljordan@gmail.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include <atomic>

#include <element/juce/data_structures.hpp>
#include <element/juce/gui_basics.hpp>
#include <element/services.hpp>
#include <element/transport.hpp>
#include <element/ui/content.hpp>


#define EL_VIEW_SESSION_VIEW "SessionView"

namespace element {

class TrackerNode;

/** Bitwig/Ableton-style clip-grid launcher view.
 *
 *  Each column maps 1:1 to a TrackerNode in the active graph.  Each
 *  scene (row) holds a sparse set of clips -- one per column at most.
 *  Clicking a clip flips its underlying vht sequence's `playing` flag
 *  via TrackerNode::setSequencePlaying.  No quantisation in Phase 3;
 *  launch is "fire on next render".
 *
 *  Visual language follows the existing tracker editor palette
 *  (monospaced font, dark background, track-tint bars).  Layout is
 *  Bitwig-shaped: top-row column headers, left-column scene labels,
 *  grid body in between.
 *
 *  Design + cookbook: ~/wine-nspa-notes/session-view-design.md
 */
class SessionView : public ContentView,
                    private juce::Timer,
                    private juce::ChangeListener
{
public:
    SessionView();
    ~SessionView() override;

    void initializeView (Services&) override;
    void didBecomeActive() override;
    void willBeRemoved() override;
    void stabilizeContent() override;

    void resized() override;
    void paint (juce::Graphics&) override;
    void mouseDown (const juce::MouseEvent&) override;
    void mouseDrag (const juce::MouseEvent&) override;
    void mouseUp   (const juce::MouseEvent&) override;
    void mouseDoubleClick (const juce::MouseEvent&) override;
    void mouseWheelMove (const juce::MouseEvent&,
                         const juce::MouseWheelDetails&) override;

    /** Snapshot-based undo entry point.  Called by the global
     *  GuiService UndoManager on the SessionViewSnapshotAction
     *  generated by writeToSession.  Replaces the sessionView VT
     *  with the supplied snapshot, re-reads to rebuild the
     *  in-memory clips_ / scenes_ / columns_ arrays, repaints.
     *  Guarded internally by applyingUndoAction_ so the
     *  writeToSession inside doesn't recursively push an action. */
    void applySessionSnapshot (const juce::ValueTree& snap);

public:
    /* Per-clip launch state.  Driven by the message thread on bang(),
     * reconciled toward engine truth in the UI timer once the audio
     * thread flips seq->playing at the scheduled boundary.  Public
     * because the Clip View popup component (declared in
     * sessionview.cpp at file scope) needs to name the type. */
    enum class LiveState : uint8_t { Stopped, WaitingToStart, Playing, WaitingToStop };

    /* Per-clip launch quantisation.  Off = immediate (next render
     * block).  All other values snap to transport beats: Beat=1,
     * Bar=beatsPerBar, TwoBars=2*bpb, FourBars=4*bpb. */
    enum class LaunchQuant : uint8_t { Off, Beat, Bar, TwoBars, FourBars };

    /* Action applied when a playing clip's sequence wraps past its end.
     *  - None: keep looping (default; vht naturally loops).
     *  - Stop: schedule immediate stop on wrap.
     *  - RestartClip: re-launch from row 0 (same clip).
     *  - NextClip: bang the clip on the next-greater sceneRow in the
     *    same column.  If none exists, falls back to Stop.
     *  - FirstClip: bang the lowest-sceneRow clip on the same column. */
    enum class FollowAction : uint8_t { None, Stop, RestartClip, NextClip, FirstClip };

private:

    struct SessionClip {
        juce::Uuid     id;
        juce::String   name;
        juce::Colour   color { 0xff'4a'7a'b5 };
        juce::uint32   trackerNodeId { 0 };  // resolves via active graph
        int            sequenceIdx   { -1 }; // -1 = unbound
        int            sceneRow      { 0 };
        int            columnIdx     { 0 };
        LaunchQuant    launchQuant   { LaunchQuant::Bar };
        FollowAction   followAction  { FollowAction::None };
        std::atomic<LiveState> state { LiveState::Stopped };
        /* UI-side cached engine state for diff-gated repaint. */
        bool           lastDrawnPlaying { false };
        int            lastDrawnPosRow  { -1 };

        SessionClip() = default;
        SessionClip (const SessionClip&) = delete;
        SessionClip& operator= (const SessionClip&) = delete;
    };

    struct SessionScene {
        juce::Uuid     id;
        juce::String   name;
        juce::Colour   color { 0xff'30'30'30 };
        /* Ableton-style per-scene overrides -- applied to the session
         * transport when the scene is launched.  Sentinel values
         * mean "no override; inherit current". */
        double         tempoOverride { -1.0 };   // bpm; -1 = no override
        int            beatsPerBar   { 0 };      // 0 = no override
        int            beatDivisor   { 0 };      // 0 = no override
    };

    struct SessionColumn {
        juce::Uuid     id;
        juce::String   name;
        juce::uint32   trackerNodeId { 0 };
    };

    void timerCallback() override;

    /* Walk the active graph, rebuild columns_ from current TrackerNodes
     * (preserving any persisted column the user authored, dropping
     * orphans).  Cheap; called on activate + graph topology changes. */
    void rescanColumns();

    void bangClip   (SessionClip&);
    void bangScene  (int sceneRow);
    void stopAllClips();

    /* Belt + suspenders for the C.1 fix.  Walks each TrackerNode and
     * forces playing=0 on every sequence not bound to a Playing /
     * WaitingToStart SessionClip.  Called from stabilizeContent +
     * didBecomeActive after rescanColumns so any sequence that
     * sneaks in with a stale playing flag (legacy save, future
     * regression, TrackerEditor experimentation) gets silenced
     * before the user hears unattributable MIDI. */
    void reconcileSequencePlaying();

    void stopColumn (int columnIdx);   // per-column stop button
    void toggleColumnMute (int columnIdx);
    void toggleColumnSolo (int columnIdx);
    bool isColumnMuted (int columnIdx) const noexcept;   // user-asserted mute
    bool isColumnSoloed (int columnIdx) const noexcept;
    /* Reconcile engine-level mute on TrackerNodes from our
     * columnUserMuted_ + columnSoloed_ vectors.  When any column is
     * soloed, every non-soloed column is muted regardless of user
     * intent; when no solo is active, mute follows user intent. */
    void applyMuteAndSoloState();
    /* sceneLaunch=true: force-start semantic used by bangScene.  An
     * already-Playing clip stays playing (no toggle-stop), a Stopped
     * clip launches, a WaitingToStop is reverted to Playing, a
     * WaitingToStart is left queued.  sceneLaunch=false (default):
     * toggle semantic used by bangClip's single-click flow -- pressing
     * a playing clip stops it. */
    void transitionClip (SessionClip&, double targetBeat, bool sceneLaunch = false);
    void applyFollowAction (SessionClip&);
    void addClipAt  (int sceneRow, int columnIdx);  // creates new vht sequence
    void deleteClip (SessionClip&);
    void openPatternEditor (SessionClip&);  // popup tracker editor at clip's seqIdx
    void openTrackerDockForClip (SessionClip&);  // surface clip in the right-side TrackerSideDock

    void addScene();                  // append at end
    void insertScene (int beforeRow);
    void deleteScene (int row);
    void renameScene (int row);
    void reorderScene (int fromRow, int toRow);  // drag-drop reorder

    void renameClip      (SessionClip&);
    void cycleClipColor  (SessionClip&);
    void pickClipColour  (SessionClip&);   // full ColourSelector popup
    void assignExistingPattern (int sceneRow, int columnIdx, int sequenceIdx);

    /* juce::ChangeListener -- receives ColourSelector edits from the
     * popup picker.  colourPickerClip_ tracks which clip the picker
     * is bound to so we can apply on each broadcast. */
    void changeListenerCallback (juce::ChangeBroadcaster*) override;

    /* Drag-and-drop within the grid.  Move = drop on another cell on
     * the SAME column (sequenceIdx remains valid).  Copy (Shift+drag) =
     * clone the underlying vht sequence via TrackerNode::cloneSequence
     * and place a new clip at the target.  Cross-column drags are no-ops
     * for v1 -- sequenceIdx is tracker-scoped, so the migration story is
     * still TBD. */
    void moveClip (SessionClip&, int newSceneRow, int newColumnIdx);
    void copyClip (SessionClip&, int newSceneRow, int newColumnIdx);

    TrackerNode* lookupTracker (juce::uint32 nodeId) const;
    SessionClip* findClip (int sceneRow, int columnIdx) const;

    /* Quantisation maths.  beatsPerBar() reads tags::beatsPerBar from
     * the session (default 4).  computeTargetBeat returns -1.0 for
     * Off quant or for a stopped transport -- both fire immediately. */
    int    beatsPerBar() const;
    double currentTransportBeat() const;
    double computeTargetBeat (double curBeat, LaunchQuant q) const;

    /* Persistence.  ValueTree is a child of the session's `objectData`
     * created by Session::setMissingProperties (`tags::sessionView`).
     * Read on initializeView; write on every mutation. */
    juce::ValueTree getOrCreateSessionViewTree();
    void readFromSession();
    void writeToSession();

    /* Snapshot-based undo state -- see public applySessionSnapshot
     * for the rationale + invariants. */
    juce::ValueTree lastCommittedSnapshot_;
    bool applyingUndoAction_ { false };

    /* Grid geometry.  Returned by laying out in resized(); also queried
     * by paint() + mouseDown() for hit-testing. */
    juce::Rectangle<int> toolbarBounds() const noexcept;
    juce::Rectangle<int> footerBounds() const noexcept;
    /* STOP + MUTE are embedded in each column's header, not a
     * separate footer row.  Bounds are relative to columnHeaderBounds. */
    juce::Rectangle<int> columnNameLabelBounds (int columnIdx) const noexcept;
    juce::Rectangle<int> columnStopButtonBounds (int columnIdx) const noexcept;
    juce::Rectangle<int> columnMuteButtonBounds (int columnIdx) const noexcept;
    juce::Rectangle<int> columnSoloButtonBounds (int columnIdx) const noexcept;
    juce::Rectangle<int> masterColumnBounds() const noexcept;
    juce::Rectangle<int> masterCellBounds (int sceneRow) const noexcept;
    juce::Rectangle<int> masterLaunchButtonBounds (int sceneRow) const noexcept;
    juce::Rectangle<int> masterTempoFieldBounds  (int sceneRow) const noexcept;
    juce::Rectangle<int> masterSigFieldBounds    (int sceneRow) const noexcept;
    juce::Rectangle<int> masterEditButtonBounds  (int sceneRow) const noexcept;
    juce::Rectangle<int> headerRowBounds() const noexcept;
    juce::Rectangle<int> sceneLabelStripBounds() const noexcept;
    juce::Rectangle<int> gridBodyBounds() const noexcept;
    juce::Rectangle<int> cellBounds (int sceneRow, int columnIdx) const noexcept;
    juce::Rectangle<int> sceneLabelBounds (int sceneRow) const noexcept;
    juce::Rectangle<int> columnHeaderBounds (int columnIdx) const noexcept;
    juce::Rectangle<int> playButtonBounds (int sceneRow, int columnIdx) const noexcept;
    juce::Rectangle<int> editButtonBounds (int sceneRow, int columnIdx) const noexcept;
    bool hitTestCell (juce::Point<int> p, int& outRow, int& outCol) const noexcept;
    bool hitTestSceneLabel (juce::Point<int> p, int& outRow) const noexcept;
    bool hitTestPlayButton (juce::Point<int> p, int& outRow, int& outCol) const noexcept;
    bool hitTestEditButton (juce::Point<int> p, int& outRow, int& outCol) const noexcept;
    bool hitTestColumnStop (juce::Point<int> p, int& outCol) const noexcept;
    bool hitTestColumnMute (juce::Point<int> p, int& outCol) const noexcept;
    bool hitTestColumnSolo (juce::Point<int> p, int& outCol) const noexcept;
    bool hitTestMasterCell (juce::Point<int> p, int& outRow) const noexcept;
    bool hitTestMasterLaunch (juce::Point<int> p, int& outRow) const noexcept;
    bool hitTestMasterTempo  (juce::Point<int> p, int& outRow) const noexcept;
    bool hitTestMasterSig    (juce::Point<int> p, int& outRow) const noexcept;
    bool hitTestMasterEdit   (juce::Point<int> p, int& outRow) const noexcept;

    /* Scene property editors -- master cell tempo/sig clicks AND the
     * scene-label "Properties..." menu both open the dedicated
     * floating Scene View (juce::DocumentWindow, non-modal,
     * self-deleting on close), matching the tracker pattern editor
     * popup convention. */
    void editSceneTempo    (int sceneRow);   // delegates to openSceneView
    void editSceneSignature (int sceneRow);  // delegates to openSceneView
    void clearSceneTempo    (int sceneRow);
    void clearSceneSignature (int sceneRow);
    void openSceneView      (int sceneRow);
    void applySceneOverridesToTransport (const SessionScene&);

    /* Public helpers used by the SceneView popup -- it edits scene
     * fields in our scenes_ array, then asks us to persist + repaint
     * the master cell. */
public:
    void notifySceneEdited (int sceneRow);
    SessionScene* sceneAt  (int sceneRow) noexcept;
    /* Used by floating popup windows (tracker pattern editor, Clip
     * View) so they can wire spacebar to the global transport. */
    void transportTogglePlay() noexcept;
    void bangClipByUuid (const juce::Uuid& clipId);

    /* Clip View popup support -- mirrors Scene View.  Right-click /
     * double-click on a clip routes here instead of the AlertWindow
     * rename / cycle-colour / etc. menu items.  Structural ops
     * (Add / Assign / Delete) stay on the right-click menu. */
    void openClipView (SessionClip&);
    void notifyClipEdited (SessionClip&);
    SessionClip* clipByUuid (const juce::Uuid&) noexcept;
private:

    /* Inline editor -- shared single TextEditor positioned over the
     * field being edited.  Replaces AlertWindow prompts so the user
     * doesn't get a modal popup stealing focus from the main app. */
    void showInlineEditor (juce::Rectangle<int> bounds,
                           const juce::String& initial,
                           std::function<void (const juce::String&)> commit);
    void hideInlineEditor();

    /* Returns true if any clip in the given scene is currently
     * Playing -- drives the master launch button's solid amber
     * state + the master scene row band. */
    bool sceneHasActiveClip (int sceneRow) const noexcept;

    /* Returns true if any clip in the given scene is currently
     * WaitingToStart -- drives the pulsing amber visual on the
     * master button + row band while clips wait for the launch
     * quant boundary to fire. */
    bool sceneHasQueuedClip (int sceneRow) const noexcept;

    /* Scroll offset for the grid body -- applied to scene-label and
     * cell y positions in their *Bounds() helpers so paint + hit
     * test both reflect the scroll state automatically. */
    int gridScrollY_ = 0;
    int maxGridScrollY() const noexcept;
    void clampScrollOffset();

    Services* services_ = nullptr;
    Transport::MonitorPtr monitor_;

    /* Label subclass that fires a callback on click.  Used for the
     * QUANT value display -- clicking pops a menu of enum options
     * rather than dropping into a text editor (typing "2 Bars" exact
     * is awkward; menu is one click). */
    class ClickableLabel : public juce::Label
    {
    public:
        std::function<void()> onClick;
        void mouseDown (const juce::MouseEvent&) override
        {
            if (onClick) onClick();
        }
    };

    /* Top toolbar -- tracker-editor-styled (juce::TextButton with the
     * same palette + juce::Label for static name / editable value
     * pairs).  Mirrors `TrackerEditor::Toolbar` so the two views
     * share a visual vocabulary. */
    juce::TextButton stopAllBtn_, rescanBtn_;
    juce::TextButton sceneMinusBtn_, scenePlusBtn_;
    juce::TextButton quantPrevBtn_,  quantNextBtn_;
    juce::Label scenesNameLabel_, scenesValueLabel_;
    juce::Label quantNameLabel_;
    ClickableLabel quantValueLabel_;

    /* Default launch quant applied to NEW clips when they're added
     * (right-click "Add new pattern" / "Assign existing pattern" or
     * drag-clone).  Persisted to the session XML at sessionView root. */
    LaunchQuant defaultLaunchQuant_ { LaunchQuant::Bar };

    void configureToolbarButton (juce::TextButton&, const juce::String&, std::function<void()>);
    void configureToolbarLabel  (juce::Label&, const juce::String& text, bool editable);
    void refreshToolbarLabels();
    void cycleDefaultQuant (int delta);   // +1 next / -1 prev
    void showQuantMenu();                 // popup picker for default quant
    void commitScenesCount (int target);  // grow / shrink to match
    juce::String formatLaunchQuant (LaunchQuant) const noexcept;

    juce::Array<SessionColumn>      columns_;
    juce::OwnedArray<SessionClip>   clips_;
    juce::Array<SessionScene>       scenes_;

    /* Phase animation for WaitingTo* outline pulse (Phase 4 will exercise). */
    int   pulsePhase_ = 0;

    /* Diff-gate for master column repaint when the session-wide
     * tempo / time signature changes outside our view. */
    double lastSessionTempo_ = -1.0;
    int    lastSessionBpb_   = -1;
    int    lastSessionBd_    = -1;

    /* Mute / solo intent now lives on each TrackerNode itself
     * (TrackerNode::getUserMuted / getSoloed) so the session view
     * and the tracker editor popup see the same state.  SessionView
     * reconciles effective Processor::setMuted from those flags on
     * every UI tick via applyMuteAndSoloState. */

    /* The most-recently-launched scene -- the "current" scene in
     * Ableton parlance.  -1 means none banged this session.  Used
     * by master-column paint to highlight the active scene row. */
    int currentSceneRow_ = -1;

    /* Drag state for clip-move/copy.  dragSource_ is set on mouseDown
     * over a clip's body (not its play/edit zones); dragActive_ trips
     * once the cursor moves past the drag threshold.  dragHover{Row,Col}
     * are the current target cell under the cursor, used to highlight
     * the drop target in paint().  mouseUp clears everything. */
    SessionClip*       dragSource_ = nullptr;
    juce::Point<int>   dragStart_  {};
    bool               dragActive_ = false;
    int                dragHoverRow_ = -1;
    int                dragHoverCol_ = -1;

    /* Scene-label drag state -- distinct from clip drag.  Mouse-down on
     * a scene label stages a potential reorder; promoted to active
     * past the drag threshold; release drops the scene at the target
     * row index. */
    int    sceneDragSource_ = -1;
    bool   sceneDragActive_ = false;
    int    sceneDragHoverRow_ = -1;

    /* ColourSelector popup state -- when a picker is open against a
     * clip, change broadcasts route through changeListenerCallback
     * to mutate clip.color.  Cleared when the picker closes (its
     * ChangeBroadcaster is destroyed, broadcasts stop arriving). */
    SessionClip* colourPickerClip_ = nullptr;

    /* Inline text editor.  Single shared child component reused
     * across every editable field (scene tempo, scene sig, future
     * clip name inspector, etc.). */
    juce::TextEditor inlineEditor_;
    std::function<void (const juce::String&)> inlineEditorCommit_;

    /* Layout constants -- sized to match the tracker editor's visual
     * rhythm (monospaced, dense, dark). */
    static constexpr int kToolbarH      = 36;
    static constexpr int kHeaderH       = 44;   // taller -- holds track name + STOP + MUTE
    static constexpr int kSceneLabelW   = 84;
    static constexpr int kColW          = 132;
    static constexpr int kRowH          = 30;
    static constexpr int kMasterColW    = 220;   // Ableton-style scene master column
    static constexpr int kSceneFooterH  = 22;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SessionView)
};

} // namespace element
